### ISSUE TITLE
Depends on the header QGuidoPainter.h that isn't installed by guidolib

### ISSUE THREAD

**Issue by yurivict** [grame-cncm/inscore#14]
Here: https://github.com/grame-cncm/inscore/blob/dev/src/inscore/interface/INScore.cpp#L43

When ```guidolib``` is installed as a package this header is missing.

**Comment by dfober** [comment]
The inscore build system has been completely revised (and greatly simplified): the dependencies are now submodules so that there is nothing to install any more and QGuidoPainter.h is an internal dependency.
The new build system is based on cmake, it's available from the dev branch.
Does it answers this issue?

**Comment by yurivict** [comment]
If I already have ```guidolib``` installed as a package, do I have to rebuild it again as part of ```inscore``` because the ```guidolib```package is missing one header?

**Comment by dfober** [comment]
now, when you build inscore, the guidolib is a submodule of the project and all the dependencies are resolved without installing any other component. Build of the guidolib (as a submodule) is automatic when you build inscore.
