### ISSUE TITLE
desktop file, icons, examples, docs aren't installed

### ISSUE THREAD

**Issue by yurivict** [grame-cncm/inscore#2]
6eeab57

**Comment by dfober** [comment]
the install target is a minimal install. The package utilities (in `package` folder) provides everything (icons, examples etc.). I didn't care of that with the install target since examples and doc are available from project. Do you think they should be installed too? is there any rationale behind that?

**Comment by yurivict** [comment]
> Do you think they should be installed too? is there any rationale behind that?

'install' target is widely expected to install the whole project under ```$(DESTDIR)$(PREFIX)``` so that it can just be copied into ```$(PREFIX)``` and run as installed. Rationale? Easy for users. There are a lot of projects that do it this way. qTox is one that comes to mind: https://github.com/qTox/qTox All python setup.py-based project do this too.

**Comment by dfober** [comment]
ok, I agree. I'll modify the install target asap.

**Comment by dfober** [comment]
done (but without doc and examples)
